---
- name: Configuration of VM
  hosts: nsapoold05
  become: true
  tasks:
    - name: run apt autoremove
      apt:
        autoremove: yes
      become: yes

    - name:  run apt clean
      apt:
        autoclean: yes
      become: yes

    - name: Change hostname
      hostname:
        name: nsapoold05

    - name: Create user marvin
      user:
        name: marvin
        password: "{{ 'NsaPool42' | password_hash('sha512') }}"
        home: /home/marvin
        createhome: yes

    - name: Change welcome message
      copy:
        content: "Welcome to nsapoold05\n"
        dest: /etc/motd
        owner: root
        group: root
        mode: '0644'

    - name: Install packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - git
        - htop
        - curl
        - sudo
        - unzip
        - python3
        - python3-pip

    - name: Install Nginx
      apt:
        name: nginx
        state: latest

    - name: Remove default Nginx configuration
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: Copy website files to Nginx root directory
      copy:
        src: /root/
        dest: /var/www/html/

    - name: Create Nginx configuration for website
      copy:
        content: |
          server {
            listen 80;
            server_name localhost;

            location / {
              root /var/www/html;
              index index.html;
            }
          }
        dest: /etc/nginx/sites-available/website

    - name: Restart Nginx
      become: yes
      systemd:
        name: nginx
        state: restarted

    - name: Install PHP and modules
      apt:
        name:
          - php-cli
          - php-fpm
          - php-json
          - php-pdo
          - php-mysql
          - php-zip
          - php-gd
          - php-mbstring
          - php-curl
          - php-xml
          - php-pear
          - php-bcmath
          - php-intl
        state: present

    - name: Set timezone in php.ini
      lineinfile:
        path: /etc/php/7.4/cli/php.ini
        regexp: '^;?date.timezone ='
        line: 'date.timezone = Europe/Paris'

  handlers:
    - name: Restart network
      become: yes
      service:
        name: network
        state: restarted
